lib/companies_web/router.ex
defmodule CompaniesWeb.Router do
  use CompaniesWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug CompaniesWeb.Plugs.Session
  end

  pipeline :set_locale do
    plug SetLocale, gettext: CompaniesWeb.Gettext, default_locale: "en"
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug CompaniesWeb.Plugs.Authorize
  end

  pipeline :admin do
    plug CompaniesWeb.Plugs.Authorize, maintainer: true
  end

  scope "/", CompaniesWeb do
    pipe_through [:browser, :set_locale]

    get "/", CompanyController, :recent
    get "/browse", CompanyController, :index
  end

  scope "/:locale/", CompaniesWeb do
    pipe_through [:browser, :set_locale]

    get "/", CompanyController, :recent
    get "/hiring", Redirect, to: "/browse?type=hiring"
    get "/browse", CompanyController, :index

    scope "/" do
      pipe_through [:auth]

      resources "/companies", CompanyController, except: [:index, :show]
      resources "/jobs", JobController, except: [:index, :show]
    end

    scope "/admin", Admin do
      pipe_through [:admin]

      resources "/pending", PendingChangeController
    end
  end

  scope "/auth", CompaniesWeb do
    pipe_through [:browser]

    get "/signout", AuthController, :signout
    get "/github", AuthController, :request
    get "/github/callback", AuthController, :callback
  end
end

lib/elixir_companies_web/router.ex
defmodule CompaniesWeb.Router do
  use CompaniesWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug CompaniesWeb.Plugs.Menu
    plug CompaniesWeb.Plugs.SiteData
    plug CompaniesWeb.Plugs.Authorize
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug CompaniesWeb.Plugs.Authorize
  end

  scope "/", CompaniesWeb do
    pipe_through :browser

    get "/", CompanyController, :recent
    get "/hiring", CompanyController, :hiring
    resources "/industries", IndustryController
    resources "/companies", CompanyController do
      resources "/jobs", JobController
    end
    resources "/users", UserController
  end

  scope "/auth", CompaniesWeb do
    pipe_through [:browser, :auth]

    get "/signout", AuthController, :signout
    get "/github", AuthController, :request
    get "/github/callback", AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", CompaniesWeb do
  #   pipe_through :api
  # end
end

lib/companies_web/views/layout_view.ex
defmodule CompaniesWeb.LayoutView do
  use CompaniesWeb, :view

  def current_location do
    CompaniesWeb.Gettext
    |> Gettext.get_locale()
    |> String.capitalize()
  end

  def known_locales do
    Gettext.known_locales(CompaniesWeb.Gettext)
  end
end

lib/companies_web/templates/layout/account.html.eex
<%= if signed_in?(@conn) do %>
  <%= if admin_session?(@conn) do %>
    <p class="control">
      <%= link to: Routes.pending_change_path(@conn, :index, locale(@conn)), class: "navbar-item button" do %>
        <span><%= gettext("Approvals") %></span>
        <span class="icon">
          <i class="fas fa-check-circle"></i>
        </span>
      <% end %>
    </p>
  <% end %>
  <p class="control">
    <%= link to: Routes.auth_path(@conn, :signout), class: "navbar-item button" do %>
      <span><%= gettext("Sign out") %></span>
      <span class="icon">
        <i class="fas fa-sign-out-alt"></i>
      </span>
    <% end %>
  </p>
<% else %>
  <p class="control">
    <%= link to: Routes.auth_path(@conn, :request), class: "navbar-item button" do %>
      <span><%= gettext("Sign in") %></span>
      <span class="icon">
        <i class="fab fa-github"></i>
      </span>
    <% end %>
  </p>
<% end %>

lib/companies_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= site_title() %></title>

    <link rel="apple-touch-icon" sizes="180x180" href="<%= Routes.static_path(@conn, "/images/favicon/apple-touch-icon.png") %>">
    <link rel="icon" type="image/png" sizes="32x32" href="<%= Routes.static_path(@conn, "/images/favicon/favicon-32x32.png") %>">
    <link rel="icon" type="image/png" sizes="16x16" href="<%= Routes.static_path(@conn, "/images/favicon/favicon-16x16.png") %>">
    <link rel="manifest" href="<%= Routes.static_path(@conn, "/images/favicon/site.webmanifest") %>">
    <link rel="mask-icon" href="<%= Routes.static_path(@conn, "/images/favicon/safari-pinned-tab.svg") %>" color="#7C6E8A">
    <meta name="msapplication-TileColor" content="#7C6E8A">
    <meta name="theme-color" content="#7C6E8A">

    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
  </head>
  <body>
    <div id="wrapper">
      <%= render "navbar.html", conn: @conn %>
      <%= render @view_module, @view_template, assigns %>
    </div>
    <%= render "footer.html", conn: @conn %>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/companies_web/templates/layout/auth_icon.html.eex
<%= if signed_in?(@conn) do %>
  <%= link to: Routes.auth_path(@conn, :signout), class: "navbar-item is-hidden-#{@version_hidden} button" do %>
    <span>Sign Out</span>
    <span class="icon">
      <i class="fas fa-sign-out"></i>
    </span>
  <% end %>
<% else %>
  <%= link to: "/auth/github", class: "navbar-item is-hidden-#{@version_hidden} button" do %>
    <span>Sign In</span>

    <span class="icon">
      <i class="fab fa-github"></i>
    </span>
  <% end %>
<% end %>

lib/companies_web/templates/layout/footer.html.eex
<footer class="footer has-text-white has-text-weight-light">
  <div class="container">
    <div class="content has-text-centered">
      <p>
      <span class="has-text-weight-semibold">
        <%= site_title() %>
      </span>
      <%= gettext("is maintained by") %>
      <%= for maintainer <- maintainers() do %>
        <a class="has-text-weight-semibold" href="https://github.com/<%= maintainer %>">
          @<%= maintainer %>
        </a>
      <% end %>
      <%= gettext(" and a team of contributors!") %>
      </p>
      <p>
      <%= gettext("Made possible with support from") %>
      <a class="has-text-weight-semibold" href="https://utensils.io">utensils.io</a>
      </p>
      <p>
        <a href="https://github.com/beam-community/elixir-companies">
          <span class="icon">
            <i class="fab fa-github" aria-hidden="true"></i>
          </span>
        </a>
      </p>
    </div>
  </div>
</footer>

lib/companies_web/templates/layout/locales.html.eex
<div class="dropdown locales is-hoverable">
  <div class="dropdown-trigger">
    <button class="button" aria-haspopup="true" aria-controls="dropdown-menu3">
      <span><%= current_location() %></span>
      <span class="icon is-small">
        <i class="fas fa-angle-down" aria-hidden="true"></i>
      </span>
    </button>
  </div>
  <div class="dropdown-menu" id="dropdown-menu3" role="menu">
    <div class="dropdown-content">
      <%= for locale <- known_locales() do %>
        <%= link String.capitalize(locale), to: "#", class: "dropdown-item", data: [locale: locale] %>
      <% end %>
    </div>
  </div>
</div>

lib/companies_web/templates/layout/navbar.html.eex
<nav id="navbar" class="navbar has-shadow is-spaced">
  <div class="container">
    <div class="navbar-brand">
      <%= link to: Routes.company_path(@conn, :recent, locale(@conn)), class: "navbar-item" do %>
        <%= img_tag Routes.static_path(@conn, "/images/elixircompanies_logo.png") %>
        &nbsp;
        <h1 class="title is-5"><%= site_title() %></h1>
      <% end %>
      <div id="navbarBurger" class="navbar-burger burger" data-target="navMain">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div> <!-- /navbarbrand -->
    <div class="navbar-menu" id="navMain">
      <div class="navbar-start">
        <%= link gettext("Home"), to: Routes.company_path(@conn, :recent, locale(@conn)), class: "navbar-item" %>
        <%= link gettext("Browse"), to: Routes.company_path(@conn, :index, locale(@conn)), class: "navbar-item" %>
        <%= link gettext("Hiring"), to: Routes.company_path(@conn, :index, locale(@conn), type: "hiring"), class: "navbar-item" %>
      </div>
      <div class="navbar-end">
        <div class="field is-grouped">
          <%= render "account.html", conn: @conn %>
          <%= render "locales.html", conn: @conn %>
        </div>
      </div>
    </div>
  </div>
</nav>