lib/companies_web/router.ex
defmodule CompaniesWeb.Router do
  use CompaniesWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug CompaniesWeb.Plugs.Session
  end

  pipeline :set_locale do
    plug SetLocale, gettext: CompaniesWeb.Gettext, default_locale: "en"
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug CompaniesWeb.Plugs.Authorize
  end

  pipeline :admin do
    plug CompaniesWeb.Plugs.Authorize, maintainer: true
  end

  scope "/", CompaniesWeb do
    pipe_through [:browser, :set_locale]

    get "/", CompanyController, :recent
    get "/browse", CompanyController, :index
  end

  scope "/:locale/", CompaniesWeb do
    pipe_through [:browser, :set_locale]

    get "/", CompanyController, :recent
    get "/hiring", Redirect, to: "/browse?type=hiring"
    get "/browse", CompanyController, :index

    scope "/" do
      pipe_through [:auth]

      resources "/companies", CompanyController, except: [:index, :show]
      resources "/jobs", JobController, except: [:index, :show]
    end

    scope "/admin", Admin do
      pipe_through [:admin]

      resources "/pending", PendingChangeController
    end
  end

  scope "/auth", CompaniesWeb do
    pipe_through [:browser]

    get "/signout", AuthController, :signout
    get "/github", AuthController, :request
    get "/github/callback", AuthController, :callback
  end
end

lib/elixir_companies_web/router.ex
defmodule CompaniesWeb.Router do
  use CompaniesWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug CompaniesWeb.Plugs.Menu
    plug CompaniesWeb.Plugs.SiteData
    plug CompaniesWeb.Plugs.Authorize
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug CompaniesWeb.Plugs.Authorize
  end

  scope "/", CompaniesWeb do
    pipe_through :browser

    get "/", CompanyController, :recent
    get "/hiring", CompanyController, :hiring
    resources "/industries", IndustryController
    resources "/companies", CompanyController do
      resources "/jobs", JobController
    end
    resources "/users", UserController
  end

  scope "/auth", CompaniesWeb do
    pipe_through [:browser, :auth]

    get "/signout", AuthController, :signout
    get "/github", AuthController, :request
    get "/github/callback", AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", CompaniesWeb do
  #   pipe_through :api
  # end
end

lib/companies/accounts.ex
defmodule Companies.Accounts do
  @moduledoc """
  The Accounts context.
  """

  import Ecto.Query, warn: false

  alias Companies.{Repo, Schema.User}

  @doc """
  Gets a single user.

  Raises `Ecto.NoResultsError` if the User does not exist.

  ## Examples

      iex> get!(123)
      %User{}

      iex> get!(456)
      ** (Ecto.NoResultsError)

  """
  def get!(id) do
    User
    |> Repo.get!(id)
    |> maintainer_status()
  end

  @doc """
  Creates a user.

  ## Examples

      iex> create(%{field: value})
      {:ok, %User{}}

      iex> create(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create(attrs \\ %{}) do
    %User{}
    |> User.changeset(attrs)
    |> Repo.insert(on_conflict: {:replace, [:token]}, conflict_target: :email)
    |> maintainer_status()
  end

  @doc """
  Gets a single user, selected by email.
  """

  def get_user_by_email(email) do
    query = from(u in User, where: u.email == ^email)

    query
    |> Repo.one()
    |> maintainer_status()
  end

  defp maintainer_status({:error, reason}) do
    {:error, reason}
  end

  defp maintainer_status({:ok, user}) do
    {:ok, maintainer_status(user)}
  end

  defp maintainer_status(%{nickname: nickname} = user) do
    %{user | maintainer: nickname in maintainers()}
  end

  defp maintainers do
    :companies
    |> Application.get_env(:site_data)
    |> Map.get(:maintainers)
  end
end

lib/companies/application.ex
defmodule Companies.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      Companies.Repo,
      # Start the endpoint when the application starts
      CompaniesWeb.Endpoint
      # Starts a worker by calling: Companies.Worker.start_link(arg)
      # {Companies.Worker, arg},
    ]

    :telemetry.attach(
      "elixir-companies-ecto",
      [:companies, :repo, :query],
      &Appsignal.Ecto.handle_event/4,
      nil
    )

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Companies.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    CompaniesWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/companies/companies.ex
defmodule Companies.Companies do
  @moduledoc """
  """

  import Ecto.Query, warn: false

  alias Companies.{PendingChanges, Repo}
  alias Companies.Schema.Company

  @doc """
  Returns the list of paginated companies.

  ## Examples

  iex> all()
  [%Company{}, ...]

  """

  def all(params \\ %{}) do
    page = Map.get(params, "page", "1")

    (c in Company)
    |> from()
    |> join(:inner, [c], i in assoc(c, :industry))
    |> join(:left, [c, _i], j in assoc(c, :jobs))
    |> predicates(params)
    |> preload([_c, i, j], industry: i, jobs: j)
    |> Repo.paginate(page: page)
  end

  @doc """
  Returns the total company count

  ## Examples

  iex> count()
  23

  """
  def count do
    query = from c in Company, select: count(c.id)

    Repo.one(query)
  end

  @doc """
  Gets a single company.

  Raises `Ecto.NoResultsError` if the Company does not exist.

  ## Examples

  iex> get!(123)
  %Company{}

  iex> get!(456)
  ** (Ecto.NoResultsError)

  """
  def get!(id), do: Repo.get!(Company, id)

  @doc """
  Submits a new company for approval.

  ## Examples

  iex> create(%{field: value}, current_user())
  :ok

  iex> create(%{field: bad_value}, current_user())
  {:error, %Ecto.Changeset{}}

  """
  @spec create(map(), map()) :: {:ok, Ecto.Schema.t()} | {:error, Ecto.Changeset.t()}
  def create(attrs, user) do
    %Company{}
    |> Company.changeset(attrs)
    |> PendingChanges.create(:create, user)
  end

  @doc """
  Updates a company.

  ## Examples

  iex> update(company, %{field: new_value})
  {:ok, %Company{}}

  iex> update(company, %{field: bad_value})
  {:error, %Ecto.Changeset{}}

  """
  def update(%Company{} = company, attrs, user) do
    company
    |> Company.changeset(attrs)
    |> PendingChanges.create(:update, user)
  end

  @doc """
  Deletes a Company.

  ## Examples

  iex> delete(company)
  {:ok, %Company{}}

  iex> delete(company)
  {:error, %Ecto.Changeset{}}

  """
  def delete(%Company{} = company, user) do
    PendingChanges.create(company, :delete, user)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking company changes.

  ## Examples

  iex> change(company)
  %Ecto.Changeset{source: %Company{}}

  """
  def change(%Company{} = company) do
    Company.changeset(company, %{})
  end

  defp predicates(query, %{"type" => <<start, finish>>}) when start in 97..122 do
    query = distinct(query, [c, _i, _j], asc: fragment("LOWER(?)", c.name))

    Enum.reduce(start..finish, query, fn char, acc ->
      or_where(acc, [c], ilike(c.name, ^"#{[char]}%"))
    end)
  end

  defp predicates(query, %{"type" => "hiring"}) do
    query
    |> exclude(:left_join)
    |> distinct([c, _i, _j], true)
    |> join(:inner, [c, _i, _j], j in assoc(c, :jobs))
    |> order_by([_c, _i, j], desc: j.inserted_at)
  end

  defp predicates(query, _) do
    query
    |> distinct([c, _i, _j], true)
    |> order_by([c, _i, _j], desc: c.inserted_at)
  end
end

lib/companies/industries.ex
defmodule Companies.Industries do
  import Ecto.Query, warn: false

  alias Companies.Repo
  alias Companies.Schema.Industry

  @doc """
  Returns the list of industries.

  ## Examples

  iex> all()
  [%Industry{}, ...]

  """

  def all do
    query =
      from i in Industry,
        order_by: i.name

    Repo.all(query)
  end
end

lib/companies/jobs.ex
defmodule Companies.Jobs do
  @moduledoc """
  The Jobs context.
  """

  import Ecto.Query, warn: false

  alias Companies.{Repo, PendingChanges}
  alias Companies.Schema.Job

  @doc """
  Returns the list of jobs.

  ## Examples

      iex> all()
      [%Job{}, ...]

  """
  def all do
    Repo.all(Job)
  end

  @doc """
  Gets a single job.

  Raises `Ecto.NoResultsError` if the Job does not exist.

  ## Examples

      iex> get!(123)
      %Job{}

      iex> get!(456)
      ** (Ecto.NoResultsError)

  """
  def get!(id), do: Repo.get!(Job, id)

  @doc """
  Submits a job listing for approval.

  ## Examples

      iex> create(%{field: value}, current_user())
      :ok

      iex> create(%{field: bad_value}, current_user())
      {:error, %Ecto.Changeset{}}

  """
  @spec create(map(), map()) :: {:ok, Ecto.Schema.t()} | {:error, Ecto.Changeset.t()}
  def create(attrs, user) do
    %Job{}
    |> Job.changeset(attrs)
    |> PendingChanges.create(:create, user)
  end

  @doc """
  Updates a job.

  ## Examples

      iex> update(job, %{field: new_value})
      {:ok, %Job{}}

      iex> update(job, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update(%Job{} = job, attrs, user) do
    job
    |> Job.changeset(attrs)
    |> PendingChanges.create(:update, user)
  end

  @doc """
  Deletes a Job.

  ## Examples

      iex> delete(job)
      {:ok, %Job{}}

      iex> delete(job)
      {:error, %Ecto.Changeset{}}

  """
  def delete(%Job{} = job, user) do
    PendingChanges.create(job, :delete, user)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking job changes.

  ## Examples

      iex> change(job)
      %Ecto.Changeset{source: %Job{}}

  """
  def change(%Job{} = job) do
    Job.changeset(job, %{})
  end
end

lib/companies/pending_changes.ex
defmodule Companies.PendingChanges do
  @moduledoc """
  The public interface to managing our pending data changes
  """

  import Ecto.Query

  alias Companies.Repo
  alias Companies.Schema.{Company, Job, Industry, PendingChange}

  def all do
    query =
      from p in PendingChange,
        where: is_nil(p.approved)

    Repo.all(query)
  end

  def approve(change_id, false) do
    case Repo.get(PendingChange, change_id) do
      nil ->
        {:error, "change not found"}

      change ->
        update_approval(change, false)
    end
  end

  def approve(change_id, true) do
    with %{action: action, changes: changes, resource: resource} = change <- Repo.get(PendingChange, change_id),
         module <- resource_module(resource),
         changeset <- changeset(module, changes),
         {:ok, _changes} <- apply_changes(action, changeset) do
      update_approval(change, true)
    else
      nil -> {:error, "change not found"}
      {:error, changeset} -> {:error, changeset}
    end
  end

  def create(changeset, action, user, note \\ "")
  def create(%{valid?: false} = changes, action, _user, _note), do: invalid_change(changes, action)
  def create(%{id: _id} = resource, action, user, note), do: create(%{data: resource, params: %{}}, action, user, note)
  def create(changes, action, user, note), do: insert_change(changes, action, user, note)

  def get(id) do
    case Repo.get(PendingChange, id) do
      nil ->
        nil

      pending_change ->
        pending_change = Repo.preload(pending_change, :user)
        current = current_values(pending_change)
        %{pending_change | original: current}
    end
  end

  defp apply_changes("create", changeset), do: Repo.insert(changeset)
  defp apply_changes("delete", record), do: Repo.delete(record)
  defp apply_changes("update", changeset), do: Repo.update(changeset)

  defp changeset(module, changes) do
    record =
      if Map.has_key?(changes, "id") do
        id = Map.get(changes, "id")
        Repo.get(module, id)
      else
        struct(module, %{})
      end

    module.changeset(record, changes)
  end

  defp current_values(%{changes: %{"id" => id}, resource: resource}) do
    module = resource_module(resource)

    module
    |> Repo.get(id)
    |> drop_ecto_fields()
    |> drop_nulls()
  end

  defp current_values(_) do
    %{}
  end

  defp drop_ecto_fields(schema) do
    schema
    |> Map.from_struct()
    |> Map.drop([:__meta__, :company, :industry, :inserted_at, :jobs, :updated_at])
  end

  defp drop_nulls(map) do
    Enum.reduce(map, %{}, fn
      {_k, nil}, acc -> acc
      {k, v}, acc -> Map.put(acc, k, v)
    end)
  end

  defp invalid_change(changes, action) do
    {:error, %{changes | repo: Repo, action: action}}
  end

  defp insert_change(%{data: resource, params: changes}, action, %{id: user_id} = user, note) do
    updated_changes =
      case Map.get(resource, :id) do
        nil -> changes
        id -> Map.put(changes, "id", id)
      end

    params = %{
      action: to_string(action),
      changes: updated_changes,
      note: note,
      resource: struct_to_string(resource),
      user_id: user_id
    }

    %PendingChange{}
    |> PendingChange.changeset(params)
    |> Repo.insert()
    |> notification(user)
  end

  defp notification({:ok, pending_change}, user) do
    pending_change
    |> Map.put(:user, user)
    |> Notify.perform()

    {:ok, pending_change}
  end

  defp notification(error, _user) do
    error
  end

  defp resource_module("company"), do: Company
  defp resource_module("industry"), do: Industry
  defp resource_module("job"), do: Job

  defp struct_to_string(%Company{}), do: "company"
  defp struct_to_string(%Industry{}), do: "industry"
  defp struct_to_string(%Job{}), do: "job"

  defp update_approval(change, approval) do
    change
    |> PendingChange.changeset(%{approved: approval})
    |> Repo.update()
  end
end

lib/companies_web/controllers/company_controller.ex
defmodule CompaniesWeb.CompanyController do
  use CompaniesWeb, :controller

  alias Companies.{Companies, Industries, Schema.Company}

  def recent(conn, _params) do
    companies_count = Companies.count()
    recent_companies = Companies.all()

    render(conn, "recent.html", recent_companies: recent_companies, companies_count: companies_count)
  end

  def index(conn, params) do
    companies = Companies.all(params)

    render(conn, "index.html", companies: companies)
  end

  def new(conn, _params) do
    changeset = Companies.change(%Company{})
    industries = Industries.all()

    render(conn, "new.html", changeset: changeset, industries: industries)
  end

  def create(conn, %{"company" => params}) do
    case Companies.create(params, current_user(conn)) do
      {:ok, _company} ->
        conn
        |> put_flash(:info, "Company created successfully.")
        |> redirect(to: Routes.company_path(conn, :recent, locale(conn)))

      {:error, %Ecto.Changeset{} = changeset} ->
        industries = Industries.all()
        render(conn, "new.html", changeset: changeset, industries: industries)
    end
  end

  def show(conn, %{"id" => id}) do
    company = Companies.get!(id)
    render(conn, "show.html", company: company)
  end

  def edit(conn, %{"id" => id}) do
    company = Companies.get!(id)
    changeset = Companies.change(company)
    industries = Industries.all()
    render(conn, "edit.html", company: company, changeset: changeset, industries: industries)
  end

  def update(conn, %{"id" => id, "company" => company_params}) do
    company = Companies.get!(id)

    case Companies.update(company, company_params, current_user(conn)) do
      {:ok, _company} ->
        conn
        |> put_flash(:info, "Company updated successfully.")
        |> redirect(to: Routes.company_path(conn, :recent, locale(conn)))

      {:error, %Ecto.Changeset{} = changeset} ->
        industries = Industries.all()
        render(conn, "edit.html", company: company, changeset: changeset, industries: industries)
    end
  end

  def delete(conn, %{"id" => id}) do
    company = Companies.get!(id)
    {:ok, _company} = Companies.delete(company, current_user(conn))

    conn
    |> put_flash(:info, "Company deleted successfully.")
    |> redirect(to: Routes.company_path(conn, :recent, locale(conn)))
  end
end

lib/companies_web/views/company_view.ex
defmodule CompaniesWeb.CompanyView do
  use CompaniesWeb, :view

  import Scrivener.HTML

  def hiring?(%{jobs: jobs}), do: length(jobs) > 0

  def hiring_ribbon(company), do: if(hiring?(company), do: "has-ribbon", else: "")

  def industry_name(%{industry: %{name: industry_name}}), do: industry_name

  def link_title(url) do
    url
    |> String.replace("http://", "")
    |> String.replace("https://", "")
    |> String.replace("www.", "")
  end

  def url_with_scheme("http://" <> _ = url), do: url
  def url_with_scheme("https://" <> _ = url), do: url
  def url_with_scheme(url, scheme \\ "https"), do: "#{scheme}://#{url}"

  def render("url.html", %{url: nil}), do: ""
  def render("blog.html", %{blog: nil}), do: ""
  def render("github.html", %{github: nil}), do: ""
  def render("location.html", %{location: nil}), do: ""

  def select_industries(industries) do
    Enum.map(industries, fn %{id: id, name: name} -> {name, id} end)
  end
end

lib/companies_web/templates/company/card.html.eex
<div class="company box <%= hiring_ribbon(@company) %>">
  <%= if hiring?(@company) do %>
    <div class="ribbon is-warning corner-top-left-ribbon">
      <span>
        <b><%= gettext("Hiring!") %></b>
      </span>
    </div>
  <% end %>
  <div class="content has-text-centered">
    <p class="title is-4 thin"><%= @company.name %></p>
    <%= if signed_in?(@conn) do %>
      <div class="company-actions-wrapper">
        <div class="toggle-company-actions">
          <i class="fas fa-ellipsis-v"></i>
        </div>
        <div class="company-actions">
          <%= link to: Routes.company_path(@conn, :edit, locale(@conn), @company) do %>
            <span class="icon"><i class="fas fa-edit"></i></span> <%= gettext("Edit") %>
          <% end %>
          <%= link to: Routes.company_path(@conn, :delete, locale(@conn), @company), method: :delete do %>
            <span class="icon"><i class="fas fa-trash-alt"></i></span> <%= gettext("Delete") %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="content company-info has-text-left">
    <p class="is-size-7">
    <span class="icon purple"><i class="fas fa-fw fa-cogs"></i></span>
    <%= industry_name(@company) %><br>

    <%= if @company.url do %>
      <span class="icon purple"><i class="fas fa-fw fa-globe"></i></span>
      <%= link link_title(@company.url), to: url_with_scheme(@company.url), target: :blank %>
      <br>
    <% end %>

    <%= if @company.blog do %>
      <span class="icon purple"><i class="fas fa-fw fa-lightbulb"></i></span>
      <%= link link_title(@company.blog), to: @company.blog, target: :blank %>
      <br>
    <% end %>

    <%= if @company.github do %>
      <span class="icon purple"><i class="fab fa-fw fa-github"></i></span>
      <%= link "GitHub", to: @company.github, target: :blank %>
      <br>
    <% end %>

    <%= if @company.location do %>
      <span class="icon purple"><i class="fas fa-fw fa-location-arrow"></i></span> <%= @company.location %><br>
    <% end %>

    <%= link to: Routes.job_path(@conn, :new, locale(@conn), company_id: @company.id) do %>
      <span class="icon purple" >
        <i class="fas fa-plus" ></i>
      </span>
        <%= gettext("Add a job") %>
      <% end %>
      <br/>
      <%= for job <- @company.jobs do %>
        <span class="icon purple"><i class="fas fa-briefcase"></i></span>
        <%= link job.title, to: url_with_scheme(job.url), target: :blank %>
        <%= if job.remote do %>&nbsp;(remote)<% end %>
        <%= if signed_in?(@conn) do %>
        &nbsp;
        [
        <%= link to: Routes.job_path(@conn, :edit, locale(@conn), job) do %>
          <span class="icon purple"><i class="fas fa-edit"></i></span>
        <% end %>
        ,
        <%= link to: Routes.job_path(@conn, :delete, locale(@conn), job), method: :delete do %>
          <span class="icon purple"><i class="fas fa-trash-alt"></i></span>
        <% end %>
        ]
        <% end %>
        <br>
      <% end %>
    </p>
  </div>
  <div class="content company-description is-size-7 has-text-centered">
    <%= @company.description %>
  </div>
</div>

lib/companies_web/templates/company/edit.html.eex
<div class="container">
  <div class="columns is-centered">
    <div class="column is-half">
      <h1 class="has-text-centered title"><%= gettext("Edit Company") %></h1>

      <%= render "form.html", Map.put(assigns, :action, Routes.company_path(@conn, :update, locale(@conn), @company)) %>

    </div>
  </div>
</div>

lib/companies_web/templates/company/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p><%= gettext("Oops, something went wrong! Please check the errors below.") %></p>
    </div>
  <% end %>

  <div class="field">
    <%= label f, :industry_id, gettext("Industry"), class: "field" %>
    <div class="control">
      <span class="select">
        <%= select f, :industry_id, select_industries(@industries) %>
      </span>
    </div>
  </div>

  <div class="field">
    <%= label f, :name, gettext("Name"), class: "field" %>
    <div class="control">
      <%= text_input f, :name, class: "input" %>
      <%= error_tag f, :name %>
    </div>
  </div>

  <div class="field">
    <%= label f, :description, gettext("Description"), class: "field" %>
    <div class="control">
      <%= textarea f, :description, class: "textarea" %>
      <%= error_tag f, :description %>
    </div>
  </div>

  <div class="field">
    <%= label f, :url, gettext("Website"), class: "field" %>
    <div class="control">
      <%= text_input f, :url, class: "input" %>
      <%= error_tag f, :url %>
    </div>
  </div>

  <div class="field">
    <%= label f, :location, gettext("Location"), class: "field" %>
    <div class="control">
      <%= text_input f, :location, class: "input" %>
      <%= error_tag f, :location %>
    </div>
  </div>

  <hr>

  <h5 class="subtitle is-5"><%= gettext("Optional fields") %></h5>

  <div class="field">
    <%= label f, :github, "GitHub", class: "field" %>
    <div class="control">
      <%= text_input f, :github, class: "input" %>
      <%= error_tag f, :github %>
    </div>
  </div>

  <div class="field">
    <%= label f, :blog, gettext("Blog website"), class: "field" %>
    <div class="control">
      <%= text_input f, :blog, class: "input" %>
      <%= error_tag f, :blog %>
    </div>
  </div>

  <div class="field is-grouped is-grouped-centered">
    <div class="control">
      <%= submit gettext("Save"), class: "button is-primary" %>
    </div>
    <div class="control">
      <%= link gettext("Back"), to: Routes.company_path(@conn, :recent, locale(@conn)), class: "button is-primary" %>
    </div>
  </div>
<% end %>

lib/companies_web/templates/company/hiring.html.eex
<section class="section">
  <div class="container">
    <div class="content">
      <h1 class="title is-3 fancy"><%= gettext("Hiring") %></h1>
      <div class="columns is-desktop is-multiline">
        <%= render CompaniesWeb.CompanyView, "companies.html", companies: @hiring_companies, conn: @conn %>
      </div> <!-- /columns -->
    </div> <!-- /content -->
  </div> <!-- /container -->
</section>

lib/companies_web/templates/company/new.html.eex
<div class="container">
  <div class="columns is-centered">
    <div class="column is-half">
      <h1 class="has-text-centered title"><%= gettext("New Company") %></h1>

      <%= render "form.html", Map.put(assigns, :action, Routes.company_path(@conn, :create, locale(@conn))) %>

    </div>
  </div>
</div>

lib/companies_web/templates/company/recent.html.eex
<section class="hero is-primary is-small">
  <div class="hero-body">
    <div class="container has-text-centered">
      <div class="content">
        <h1 class="title is-4 thin">
          <%= site_description() %>
        </h1>
        <p>
          <%= raw gettext(
            "With <span class='has-text-weight-semibold'>%{companies_count}</span> and counting...",
            companies_count: @companies_count) %>
        <p>

        <%= if signed_in?(@conn) do %>
          <%= link to: Routes.company_path(@conn, :new, locale(@conn)), class: "button is-white is-rounded is-outlined" do %>
            <span class="icon">
              <i class="fab fa-github"></i>
            </span>
            <span class="has-text-weight-semibold"><%= gettext("Add a company") %></span>
          <% end %>
        <% else %>
          <%= link to: Routes.auth_path(@conn, :request), class: "button is-white is-rounded is-outlined" do %>
            <span class="has-text-weight-semibold"><%= gettext("Sign in & list free") %></span>
            <span class="icon">
              <i class="fab fa-github"></i>
            </span>
          <% end %>
        <% end %>
        </p>
      </div>
    </div>
  </div>
</section>
<section class="section">
  <div class="container">
    <div class="content">
      <h1 class="title is-3 fancy"><%= gettext("Recent Additions") %></h1>
      <div class="columns is-mobile is-multiline">
        <%= for company <- @recent_companies do %>
          <div class="column is-full-mobile is-half-tablet is-one-third-desktop is-one-quarter-widescreen">
            <%= render "card.html", company: company, conn: @conn %>
          </div>
        <% end %>
      </div> <!-- /columns -->
      <div class="container has-text-centered">
        <%= link gettext("Browse full list"), to: Routes.company_path(@conn, :index, locale(@conn)), class: "button is-link" %>
      </div>
    </div> <!-- /content -->
  </div> <!-- /container -->
</section>

lib/companies_web/templates/company/show.html.eex
<h1><%= gettext("Show Company") %></h1>

<ul>

  <li>
    <strong><%= gettext("Name:") %></strong>
    <%= @company.name %>
  </li>

  <li>
    <strong><%= gettext("Description:") %></strong>
    <%= @company.description %>
  </li>

  <li>
    <strong><%= gettext("Url:") %></strong>
    <%= @company.url %>
  </li>

  <li>
    <strong>Github:</strong>
    <%= @company.github %>
  </li>

  <li>
    <strong><%= gettext("Location:") %></strong>
    <%= @company.location %>
  </li>

  <li>
    <strong><%= gettext("Blog:") %></strong>
    <%= @company.blog %>
  </li>

</ul>

<span><%= link gettext("Edit"), to: Routes.company_path(@conn, :edit, locale(@conn), @company) %></span>
<span><%= link gettext("Back"), to: Routes.company_path(@conn, :index, locale(@conn)) %></span>